version: '3.7'

services:
  libremdb:
    container_name: libremdb
    hostname: libremdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3009:3000"
    env_file: .env
    depends_on:
      - libremdb_redis
    restart: always
    user: 65534:65534
    read_only: true
    tmpfs:
      - /opt/app/.next/cache/:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - libremdb

  libremdb_redis:
    container_name: libremdb_redis
    hostname: libremdb_redis
    image: redis:latest
    restart: always
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    networks:
      - libremdb

networks:
  libremdb:
